encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.wiki, name="wiki"),
    path("error", views.error, name="error"),
    path("search", views.search, name="search"),
    path("save", views.save, name="save"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("random", views.random_page, name="random")
]

mail/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # API Routes
    path("emails", views.compose, name="compose"),
    path("emails/<int:email_id>", views.email, name="email"),
    path("emails/<str:mailbox>", views.mailbox, name="mailbox"),
]

project3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail.urls'))
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import re
from django.http import request
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django import forms
import random


class WikiForm(forms.Form):
    attributes = {'class': "form-control", 'style': 'width:600px;'}
    title = forms.CharField(label='Enter a title', max_length=100, widget=forms.TextInput(attrs=attributes))
    content = forms.CharField(label = "Content", widget=forms.Textarea(attrs=attributes))

from . import util
from markdown2 import Markdown

entry_list = util.list_entries()

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": entry_list
    })

def wiki(request, title):
    markdowner = Markdown()
    page_content = util.get_entry(title)

    if page_content == None:
        return render(request, "encyclopedia/error.html", {
            "error": "Page not found"
        })
    else:
        converted_to_html = markdowner.convert(page_content)
        return render(request, "encyclopedia/wiki.html", {
            "content": converted_to_html,
            "title": title
        })

def search(request):

    if request.method == "POST":
    
        query = request.POST.get("q")
    
        if util.get_entry(query) == None:
            matching_list = []
            for i in entry_list:
                if query.lower() in i.lower():
                    matching_list.append(i)
                
            return render(request, "encyclopedia/search.html", {
                "results": matching_list
            })
    
        else:
            return redirect(f"/wiki/{query}")

def save(request):
    if request.method == "POST":
        form = WikiForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if title in entry_list:
                return render(request, "encyclopedia/error.html", {
                    "error": "Wiki already exists"
                })
            else:
                util.save_entry(title, content)
                return HttpResponseRedirect(f"/wiki/{title}")
        else:
            return render(request, "encyclopedia/save.html", {
                "form": form
            })

    if request.method == "GET":
        return render(request, "encyclopedia/save.html", {
            "form": WikiForm()
        })

def edit(request, title):
    if request.method == "POST":
        form = WikiForm(request.POST)
        if form.is_valid():
            edited_title = form.cleaned_data["title"]
            edited_content = form.cleaned_data["content"]
            util.save_entry(edited_title, edited_content)
            return HttpResponseRedirect(f"/wiki/{edited_title}")

    
    if request.method == "GET":
        form = WikiForm({'title': title, 'content': util.get_entry(title)})
        return render(request, "encyclopedia/edit.html", {
            "form": form,
            "title": title
        })

def random_page(request):
    return redirect(f"/wiki/{random.choice(entry_list)}")

def error(request):
    return render(request, "encyclopedia/error.html")

encyclopedia/templates/encyclopedia/edit.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
Edit
{% endblock %}

{% block body %}

<h1>{{title}}</h1>

<form action="/edit/{{title}}" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" class="btn btn-primary">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Error
{% endblock %}

{% block body %}
<h2 id="error-header">
    {{error}}
</h2>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:save' %}">Create New Page</a>
                </div>
                <div>
                    <a href="/random">
                    Random Page
                    </a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/save.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Create
{% endblock %}

{% block body %}
<form action="{% url 'encyclopedia:save' %}" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" class="btn btn-primary">
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
Search
{% endblock %}

{% block body %}
    <ul>
        {% for entry in results %}
        <li><a href="/wiki/{{entry}}">{{entry}}</a></li>
        {% empty %}
            <p>No Entries matching the query found</p>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{title}}
{% endblock %}

{% block body %}
<a href="/edit/{{title}}" class="edit-link">Edit</a>
        {{content|safe}}
{% endblock %}